// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvKX-mjoJw3eYUajhb52kPYFuEKvJkUmo',
    appId: '1:249906887349:web:9178a2c173959f8dbc5cfc',
    messagingSenderId: '249906887349',
    projectId: 'traliogo-55b54',
    authDomain: 'traliogo-55b54.firebaseapp.com',
    storageBucket: 'traliogo-55b54.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvKX-mjoJw3eYUajhb52kPYFuEKvJkUmo',
    appId: '1:249906887349:android:ANDROID_APP_ID',
    messagingSenderId: '249906887349',
    projectId: 'traliogo-55b54',
    storageBucket: 'traliogo-55b54.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvKX-mjoJw3eYUajhb52kPYFuEKvJkUmo',
    appId: '1:249906887349:ios:IOS_APP_ID',
    messagingSenderId: '249906887349',
    projectId: 'traliogo-55b54',
    storageBucket: 'traliogo-55b54.firebasestorage.app',
    iosBundleId: 'com.example.trailogoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvKX-mjoJw3eYUajhb52kPYFuEKvJkUmo',
    appId: '1:249906887349:macos:MACOS_APP_ID',
    messagingSenderId: '249906887349',
    projectId: 'traliogo-55b54',
    storageBucket: 'traliogo-55b54.firebasestorage.app',
    iosBundleId: 'com.example.trailogoApp',
  );
}